sudo: required
services:
- docker
language: node_js
node_js:
- 6.10.2
branches:
  only:
  - master
  - travis
install:
- "./build.sh"
deploy:
after_success:
- docker login -u $DOCKER_U -p $DOCKER_P -e $DOCKER_E
- docker push ezuce/redis
- docker push ezuce/mongodb
env:
  matrix:
  - secure: BaMasD65Hkqs5xj2DcpCG7uUeqgRZMajmtgPEpVs/yzrY4gKKW1JTi42UUFochdWBTS7gk1ag/iOG5i1frNq4ClLWXkN3DPEGlz5R8TaSfAPtsuOEFB9xpPqZBQXk6DhmPQ19akFLKH+KO2Mzr6ii/hOP9vb/RmYBwYG2fB51C9B5prO1V4QZUuWGakRJX8ssTZls1FIY7oq3cICDySX9/G3l+nWWpVihxnoJ+nR463WKFZMl4p5/pSqe4iRX3CQE5yxiCdKtsaqrgd9oWhfqZkqPVbhR/HMfthKEUPFCLg6YnW+Fa5WPi43lQq7VcVKcRZ/s6YUjqGlSwuH906RZvyqhrc1iEUq049dDpK/DCcL1O/or4XLv94JV0oOBsoDqoG/z+bF09OpCu53CJBPJ8s1hOUd1eDYKhKdGS0d+jjp9XdXV6toTDgkiPDFYyFAmX0dsntBtUDrmnpXV1eqNHIkdjpNzSZ1fnb2IvHNmjoqdPP7lSNhW0kXO7hS6OjNJoD9uwqzwhRdj/yHjEE/5oOFB8Iobu+YayVjteHW/AOf1WBzOSD443gs3iSlO7TRNrVx3kHye0mQC3BSO7iN1R9zPZMRPzT6fq6pAAiY1oXzNqFileNYgqTWkdzOkp0SmY0+O5yGUqsHpoAP5gGQPjDFaasedE+s2fP0D4Ko/Ac=
  - secure: vzAEsQwbZ2Pc4BHFXkoDzqWQ/c5ZfJTYzt+HG8zYDEP1m3l/6h+7h5PjiFwY3rMdJ2lIbJamG+2+EYLHBiK0fRWzPp6QJzxmmL05TA9UO8PdH0Tv4CFqvU8hocmvv1OadcC2SyvDSuGYM1PIMg10NJW41rrPSQ3KGMvT8eYiwS/WvePRmXQdoNOZS59vytL7cRwUjjpPKSEYtZghI2Fqrl1OUrcwoIVEPGCRQ1Gi3WV0C8t0ajwDQD7l0xkojkUMj/0JLpBpxP3FyKivUTPMxmlVwyMqRZMu6P52RPFRj9GsU1Mm8KKypUKd5R/VRx3c2KEmAtY+cOakMm6MKq/Z7Xw/ch1li8hyCOMH7/90dSqJ1JTuGZqk1AwcKXSLOM56WA4sKvHxVpYHKSQuPLcPYq1fFselgb8av/jv7VBexBb7hOo1umwj2/aTzlo25qLVKLMvnQlmmf0mqvveFCiJWVCsaCAaZm6p9+n6FM1MFA7/BrbSvdw8485aRMWXmNCYtTqrf2WZaNjBzoO9zhTwvuY5lB1dZLmpVgKnjHrBPypTa0jthoOIP2Rh60ft1h6ADBcqunFiJb46y9dfzIAWvJ/48HAvb/HYOQrC0I8GxpzwsQPQ6xB14edr468WQeR19A0IPy8XOe8B4h3bBuYA5m9aqK3JwGl2AO327CiD1pY=
  - secure: Vz+MAyYKwVDpL1i7iNlASCwlv8kzrm8hp8v+U2sf+aAEA8JeQ2hpupLMSKM25RDPqjF92Q6h5d6g97xKd6n5Kam6g8yz+WV3myI+zJ2wg5t1CmgwTZkK3CWduUTZ4am/8pUUskb+q0j9tWQrbhgEbUFSyzXd9cL4UwesuDJztCEPq4xRMN5E8fqUppdo6d2Dd57v5GYq48fZdkdE8vm2PDkj4rLKJwwcVym0HbpfL/vNljc9YQxAxyAFXfPlN2/ao/Rxykuq3IR+WRayTM8K6zQraZwd/Gc+yelbzVRRSbIi/x2yiHkh6LS139XL+XFeo9ytR5noBIHEbc+5OkhQqwaFRVQdKLYWh4GB+m2hqGOqPn0cPaqPi5Lu3OXH3d3UwlwdqEJzvtBiYJI4LeHQLg3nuwXu6nF8f/paCHgrdp2ASuey1Vasr/6XSNxoYQ0tDfv34xtiG1qCPfy1ahrCqxJiuJ8E1xOPl1D7cU39GrrgoPgIQ3v+olDao8o2Olqd2qCwPRcGVY8uz5aYdYPHzIqBTViiD2QNlaXY5x70Go278RnCG2xT8Nxeq4tGdq90M49WNYc5LHwASbPNc9Fd2KOUMNe4/NU8xJZ/UoEcpJXfPFnG8kjSzqk18LNBuCHx2BHwG1A9SN35+UnYfYapur1ZxMnZX/YcdjKuUUsFLeI=
