sudo: required
services:
- docker
language: node_js
node_js:
- 6.10.2
branches:
  only:
  - master
  - travis
install:
- "./build.sh"
deploy:
after_success:
- docker login -u="$DOCKER_U" -p="$DOCKER_P"
- docker push ezuce/redis
- docker push ezuce/mongodb
