  sipxregistrar:
    image: ezuce/sipxregistrar
    ports:
      - "5070:5070"
      - "5075:5075"
      - "5077:5077"
    volumes:
      - ./sipxconfig/run/conf/1/:/usr/local/sipx/etc/sipxpbx/
      - ./bootstrap/mongo-client.ini:/usr/local/sipx/etc/sipxpbx/mongo-client.ini
      - ./sipxconfig/run/conf/1/resource-limits-registrar.ini:/usr/local/sipx/etc/sipxpbx/resource-limits.ini
    external_links:
      - mongo:$MONGO_HOST
      - postgres:postgres.ezuce
    container_name: sipxregistrar
    restart: on-failure
