  version: "3"
  services:
    bootstrap:
      build: bootstrap/.
      environment:
        - MONGO_HOST
        - DOMAIN
        - SIP_DOMAIN
        - REALM
        - HOST_NAME
        - REGISTRAR_HOST
        - NETWORK_NAME
        - NETWORK_SUBNET
        - PROXY_HOST
        - DNS_IP
        - MACHINE_IP
      volumes:
        - ./bootstrap:/bootstrap
      container_name: bootstrap
      restart: on-failure
      networks:
        - ezuce
    dns:
      build: dns/.
      volumes:
        - ./dns/srv/docker/bind9:/named
      container_name: named
      restart: on-failure
      networks:
         ezuce:
           ipv4_address: $DNS_IP
    mongo:
      image: mongo
      ports:
       - "27017:27017"
      volumes:
       - ./mongodb-sipxconfig/etc/mongodb.conf:/etc/mongo.config
       - ./mongodb-sipxconfig/mongo-data/data:/data/db
      command: mongod --config /etc/mongo.config
      hostname: $MONGO_HOST
      container_name: mongo
      networks:
        - ezuce
    mongo-init:
      build: mongodb-init/.
    #  links:
    #   - mongo:mongo
      command: /usr/bin/initialize-mongodb.sh
      container_name: mongo-init
      networks:
        - ezuce
    postgres:
      image: ezuce/postgres
      ports:
       - "5432:5432"
      volumes:
        - ./postgres-sipxconfig/pg-data/pgdata:/var/lib/postgresql/data
      container_name: postgres.ezuce
      networks:
        - ezuce
    sipxconfig:
      image: ezuce/sipxconfig
      ports:
        - "12000:12000"
      volumes:
        - ./sipxconfig/run/conf/:/usr/local/sipx/etc/sipxpbx/conf/
        - ./bootstrap/mongo-client.ini:/usr/local/sipx/etc/sipxpbx/mongo-client.ini
        - ./bootstrap/sipxconfig.properties:/usr/local/sipx/etc/sipxpbx/sipxconfig.properties
        - ./bootstrap/postgres-pwd.properties:/usr/local/sipx/etc/sipxpbx/postgres-pwd.properties
        - ./bootstrap/ssl-web.keystore:/usr/local/sipx/etc/sipxpbx/ssl/ssl-web.keystore
      container_name: sipxconfig
      hostname: $HOST_NAME
      domainname: $DOMAIN
      restart: on-failure
      networks:
        - ezuce
    nginx:
      image: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx-sipxconfig/etc/sipxconfig.conf:/etc/nginx/conf.d/default.conf
      container_name: nginx
      networks:
        - ezuce
    supervisor:
      build: supervisor/.
      image: ezuce/supervisor
      environment:
        - NETWORK_SUBNET=${NETWORK_SUBNET}
        - MACHINE_IP=${MACHINE_IP}
        - PROXY_HOST=${PROXY_HOST}
        - SIP_DOMAIN=${SIP_DOMAIN}
        - HOST_PWD=${PWD}
      volumes:
        - ./sipxconfig/run/conf:/usr/local/sipx/etc/sipxpbx/conf
        - /var/run/docker.sock:/var/run/docker.sock
      container_name: supervisor
      privileged: true
      restart: on-failure
      networks:
        - ezuce
  networks:
    ezuce:
      external:
        name: ezuce
