  version: "3"
  services:
    sipxregistrar:
      image: ezuce/sipxregistrar
      dns: $DNS_IP
      ports:
        - "5070:5070"
        - "5075:5075"
        - "5077:5077"
      volumes:
        - ./sipxconfig/run/conf/1/:/usr/local/sipx/etc/sipxpbx/
        - ./bootstrap/mongo-client.ini:/usr/local/sipx/etc/sipxpbx/mongo-client.ini
      container_name: sipxregistrar
      hostname: $REGISTRAR_HOST
      restart: on-failure
      networks:
         ezuce:
           ipv4_address: $REG_IP

    sipxproxy:
      image: ezuce/sipxproxy
      dns: $DNS_IP
      ports:
        - "5060:5060"
        - "5061:5061"
      depends_on:
        - sipxregistrar
      volumes:
        - ./sipxconfig/run/conf/1/:/usr/local/sipx/etc/sipxpbx/
        - ./bootstrap/mongo-client.ini:/usr/local/sipx/etc/sipxpbx/mongo-client.ini
      container_name: sipxproxy
      hostname: $PROXY_HOST
      restart: on-failure
      networks:
         ezuce:
           ipv4_address: $PROXY_IP

  networks:
    ezuce:
      external:
        name: ezuce
